import type { Metadata } from "next"
import React from "react"

import { AppSidebar } from "@/components/sidebar/app-sidebar"
import { HeaderSidebar } from "@/components/sidebar/header-sidebar"
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function DashboardLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode
  modal: React.ReactNode
}>) {
  return (
    <SidebarProvider>
      <AppSidebar variant={"inset"} />
      <SidebarInset>
        <HeaderSidebar />
        <main>
          {children}
          {modal}
        </main>
      </SidebarInset>
    </SidebarProvider>
  )
}
