import type { Metadata } from "next"
import { cookies } from "next/headers"
import React from "react"

import { AppSidebar } from "@/components/sidebar/app-sidebar"
import { HeaderSidebar } from "@/components/sidebar/header-sidebar"
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar"
import { getUserMetadata } from "@/server/data-access/get-user-metadata"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function DashboardLayout({
  children,
  detail,
}: Readonly<{
  children: React.ReactNode
  detail: React.ReactNode
}>) {
  const cookieStore = await cookies()
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true"

  const user = await getUserMetadata()

  return (
    <SidebarProvider defaultOpen={defaultOpen}>
      <AppSidebar variant="floating" user={user} />
      <SidebarInset className="overflow-hidden">
        <HeaderSidebar />
        <main>
          <div className="mx-auto flex w-full flex-1 flex-col px-4 py-2 contain-inline-size">
            {children}
          </div>
          {detail}
        </main>
      </SidebarInset>
    </SidebarProvider>
  )
}
